roadmaps/2022.md
⚠️ This is the core-team roadmap and NOT a product roadmap. This roadmap completes the roadmap of the product team but is not a duplication!
Sorry for the delay. The content should be not a surprise, only topics we discussed I finally put in public 😇
=> Add roadmap 2022

meilisearch-release-changelog/v0.29.0.md
=> Changelog v0.29.0

roadmaps/2022.md
- Update Q3 2022 roadmap
- Create Q4 2022 roadmap
=> Add Q4 2022 roadmap

meilisearch-release-changelog/v0.30.0.md
This PR corresponds to v0.30.0 changelogs
=> Add changelog v0.30.0

resources/versioning-policy.md
Pinging @meilisearch/engine-team for your information, so that you know the guide is here, in public 😇 
Part of this issue: https://github.com/meilisearch/meilisearch/issues/3191
=> Add versioning policy

resources/meilisearch-release.md
Related to https://github.com/meilisearch/meilisearch/issues/3211
=> Use the new RC format

resources/versioning-policy.md
Following this internal discussion: https://meilisearch.slack.com/archives/CD7Q2UKGB/p1670853892183669
@brunoocasali and @irevoire I would like to have your review on this 😇
=> Update versioning-policy.md to add the type addition condition

resources/versioning-policy.md
Pinging @bidoubiwa since you are now the maintainer of mini-dashboard
Also pinging @Kerollmops for your information, and @irevoire because you are the one who mentioned it internally.
=> Update versioning-policy.md about mini dashboard

meilisearch-release-changelog/v1.0.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/2898
👉 👉 👉 [Rendered](https://github.com/meilisearch/engine-team/blob/changelogs-v1.0.0/meilisearch-release-changelog/v1.0.0.md) 👈 👈 👈
=> Add v1.0.0 changelogs

resources/versioning-policy.md
Also pinging @brunoocasali to inform you we clarified our versioning policy regarding the integration tools 😊
=> Add warning about the tool in versioning guide

meilisearch-release-changelog/v1.1.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/3298
=> Add v1.1.0 changelogs

resources/experimental-features.md, resources/prototypes.md
@meilisearch/engine-team for your information, I wrote a quick guide about what is prototype: nothing you should be surprised of
Let me know if there is something you would like to see improved
=> Add prototype guide

meilisearch-release-changelog/v1.2.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/3558
=> Changelogs v1.2.0

resources/meilisearch-release.md
Following our shadowing session
=> Add TODO template to RC process

resources/meilisearch-release.md
Hey, just some small modifications that I think will improve the experience of the next beginner doing its first release
=> Small improvements over the new release guide

meilisearch-release-changelog/v1.7.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/4265
=> Changelogs of v1.7.0

issue-templates/dependency-issue.md
Must be merged once https://github.com/meilisearch/meilisearch/pull/4706 is merged
=> Propose a new way to update dependencies

meilisearch-release-changelog/v1.11.0.md
Fixes: https://github.com/meilisearch/meilisearch/issues/4832
=> Changelog v1.11.0

meilisearch-release-changelog/v1.12.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/4966
=> Changelogs v1.12.0

meilisearch-release-changelog/v1.13.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/5074.
=> Changelog v1.13

meilisearch-release-changelog/v1.14.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/5269.
=> Changelog v1.14

meilisearch-release-changelog/changelog-template.md, meilisearch-release-changelog/v1.15.0.md
Fixes https://github.com/meilisearch/meilisearch/issues/5434.
=> Changelog v1.15
